import {useState,useEffect} from 'react';
import {updateCustomerProfile} from '../../services/customerAuthService';
export default function CustomerLocationCard({customer,onSaved}){
 const [lat,setLat]=useState(''),[lng,setLng]=useState(''),[accuracy,setAccuracy]=useState(null),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
 useEffect(()=>{setLat(customer.deliveryLocation?.latitude ?? '');setLng(customer.deliveryLocation?.longitude ?? '');},[customer.deliveryLocation]);
 const valid=lat!==''&&lng!==''&&Number.isFinite(Number(lat))&&Number.isFinite(Number(lng))&&Math.abs(Number(lat))<=90&&Math.abs(Number(lng))<=180;
 function locate(){if(!navigator.geolocation){setMessage('Location is unavailable. Enter map coordinates below.');return;}setBusy(true);setMessage('Finding your location...');navigator.geolocation.getCurrentPosition(p=>{setLat(p.coords.latitude);setLng(p.coords.longitude);setAccuracy(p.coords.accuracy);setBusy(false);setMessage('Check the pin, then save it for deliveries.');},()=>{setBusy(false);setMessage('Location could not be read. Allow location access or enter coordinates.');},{enableHighAccuracy:true,timeout:15000,maximumAge:0});}
 async function save(){if(!valid||busy)return;setBusy(true);try{const result=await updateCustomerProfile({deliveryLocation:{latitude:Number(lat),longitude:Number(lng),...(accuracy!==null?{accuracy}:{})}});onSaved(result.customer);setMessage('Delivery location saved.');}catch{setMessage('Location was not saved. Please retry.');}finally{setBusy(false);}}
 return <section className="mt-6 rounded-2xl border border-emerald-100 bg-white p-5 shadow-sm"><p className="text-xs font-bold uppercase tracking-widest text-emerald-700">YOUR DELIVERY PIN</p><h2 className="mt-2 text-xl font-bold">Make your doorstep easy to find</h2><p className="my-3 text-sm text-slate-600">Save your current location for the delivery team. Your written address stays unchanged.</p><button type="button" disabled={busy} onClick={locate} className="rounded-xl bg-emerald-700 px-4 py-3 text-white">Use current location</button><div className="my-4 grid grid-cols-2 gap-3">{[['Latitude',lat,setLat],['Longitude',lng,setLng]].map(([label,value,set])=><label key={label} className="text-sm">{label}<input className="mt-1 w-full rounded-xl border p-3" aria-label={label} type="number" step="any" value={value} onChange={e=>{set(e.target.value);setAccuracy(null);}}/></label>)}</div>{accuracy!==null&&<p className="mb-3 text-sm">GPS accuracy: about {Math.round(accuracy)} metres. Check the pin before saving.</p>}<div className="flex flex-wrap items-center gap-4">{valid&&<a className="text-emerald-700 underline" target="_blank" rel="noreferrer" href={'https://www.google.com/maps/search/?api=1&query='+encodeURIComponent(lat+','+lng)}>Preview pin in Maps</a>}<button type="button" disabled={!valid||busy} onClick={save} className="rounded-xl bg-slate-900 px-4 py-3 text-white disabled:opacity-40">{busy?'Please wait...':'Save delivery pin'}</button></div><p role="status" className="mt-3 text-sm">{message}</p></section>;
}
