import { useEffect, useRef, useState } from 'react';
import api from '../services/api';
const statuses=['Pending','Confirmed','Preparing','Out for Delivery','Delivered','Cancelled'];
export default function WebsiteOrders(){
 const [orders,setOrders]=useState([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[filter,setFilter]=useState('Pending'),[search,setSearch]=useState(''),[drafts,setDrafts]=useState({}),[saving,setSaving]=useState({});
 const pending=useRef(new Set());
 useEffect(()=>{let active=true;api.get('/website-orders').then(result=>{if(active)setOrders(result.data.data||[]);}).catch(()=>{if(active)setError('Unable to load website orders.');}).finally(()=>{if(active)setLoading(false);});return()=>{active=false;};},[]);
 const save=async order=>{
  if(pending.current.has(order._id))return;pending.current.add(order._id);setSaving(old=>({...old,[order._id]:true}));setError('');
  const status=drafts[order._id]||order.orderStatus;
  try{const result=await api.put('/website-orders/'+order._id,{orderStatus:status});setOrders(old=>old.map(item=>item._id===order._id?result.data.data:item));setDrafts(old=>{const next={...old};delete next[order._id];return next;});}
  catch{setError('Order could not be updated. Your selection is retained.');}
  finally{pending.current.delete(order._id);setSaving(old=>({...old,[order._id]:false}));}
 };
 const visible=orders.filter(order=>(filter==='All'||order.orderStatus===filter)&&[order.customerName,order.mobileNumber,order.deliveryAddress].join(' ').toLowerCase().includes(search.toLowerCase()));
 return <div className="mx-auto max-w-6xl p-4 sm:p-8"><div className="mb-6"><h2 className="text-2xl font-bold text-slate-900">Website orders</h2><p className="mt-2 text-sm text-slate-500">Review online orders and update their existing fulfillment status.</p></div><div className="mb-6 flex flex-wrap gap-3"><input aria-label="Search website orders" placeholder="Search customer, phone or address" value={search} onChange={event=>setSearch(event.target.value)} className="min-w-0 flex-1 rounded-xl border border-slate-200 px-4 py-3"/><select aria-label="Order status filter" value={filter} onChange={event=>setFilter(event.target.value)} className="rounded-xl border border-slate-200 px-4 py-3">{['All',...statuses].map(status=><option key={status}>{status}</option>)}</select></div>
 {error&&<p role="alert" className="mb-5 text-sm text-red-600">{error}</p>}{loading?<p role="status">Loading orders…</p>:!visible.length?<p className="rounded-2xl bg-white p-6 text-slate-500">No matching orders.</p>:<div className="space-y-4">{visible.map(order=><article key={order._id} className="rounded-2xl border border-slate-200 bg-white p-5"><div className="flex flex-wrap justify-between gap-4"><div><h3 className="font-bold text-slate-900">{order.customerName}</h3><p className="mt-1 text-sm text-slate-500">{order.mobileNumber} · {new Date(order.orderDate).toLocaleDateString('en-IN')}</p><p className="mt-2 text-sm text-slate-600">{order.deliveryAddress}</p></div><div className="text-right"><p className="font-bold text-slate-900">₹{Number(order.totalAmount||0).toLocaleString('en-IN')}</p><p className="mt-1 text-xs text-slate-500">Payment: {order.paymentStatus}</p></div></div><ul className="my-4 text-sm text-slate-600">{order.items?.map((item,index)=><li key={index}>{item.quantity} × {item.name} · {item.mealType}</li>)}</ul>{order.specialInstructions&&<p className="mb-4 text-sm text-slate-500">{order.specialInstructions}</p>}<div className="flex flex-wrap items-center gap-3"><select aria-label={'Status for '+order.customerName} disabled={saving[order._id]} value={drafts[order._id]||order.orderStatus} onChange={event=>setDrafts(old=>({...old,[order._id]:event.target.value}))} className="rounded-xl border border-slate-200 px-3 py-2">{statuses.map(status=><option key={status}>{status}</option>)}</select><button type="button" disabled={saving[order._id]||!drafts[order._id]||drafts[order._id]===order.orderStatus} onClick={()=>save(order)} className="rounded-xl bg-blue-600 px-4 py-2 text-sm font-semibold text-white disabled:opacity-50">{saving[order._id]?'Saving…':'Update status'}</button></div></article>)}</div>}</div>;
}
